require "encoji/version"

module Encoji
  extend self

  ATTRIBUTES = [
    # Codepoints | Cheat sheet codes | Description

    # People
    ["\u{1F604}", [:smile], "SMILING FACE WITH OPEN MOUTH AND SMILING EYES"],
    ["\u{1F606}", [:laughing], "SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES"],
    ["\u{1F60A}", [:blush], "SMILING FACE WITH SMILING EYES"],
    ["\u{1F603}", [:smiley], "SMILING FACE WITH OPEN MOUTH"],
    ["\u{263A}" , [:relaxed], "WHITE SMILING FACE"],
    ["\u{1F60F}", [:smirk], "SMIRKING FACE"],
    ["\u{1F60D}", [:heart_eyes], "SMILING FACE WITH HEART-SHAPED EYES"],
    ["\u{1F618}", [:kissing_heart], "FACE THROWING KISS"],
    ["\u{1F61A}", [:kissing_closed_eyes], "KISSING FACE WITH CLOSED EYES"],
    ["\u{1F633}", [:flushed], "FLUSHED FACE"],
    ["\u{1F625}", [:relieved], "DISAPPOINTED BUT RELIEVED FACE"],
    ["\u{1F60C}", [:satisfied], "RELIEVED FACE"],
    ["\u{1F601}", [:grin], "GRINNING FACE WITH SMILING EYES"],
    ["\u{1F609}", [:wink], "WINKING FACE"],
    ["\u{1F61C}", [:stuck_out_tongue_winking_eye, :wink2], "FACE WITH STUCK OUT TONGUE AND WINKING EYE"],
    ["\u{1F61D}", [:stuck_out_tongue_closed_eyes], "FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES"],
    ["\u{1F600}", [:grinning], "GRINNING FACE"],
    ["\u{1F617}", [:kissing], "KISSING FACE"],
    ["\u{1F619}", [:kissing_smiling_eyes], "KISSING FACE WITH SMILING EYES"],
    ["\u{1F61B}", [:stuck_out_tongue], "FACE WITH STUCK-OUT TONGUE"],
    ["\u{1F634}", [:sleeping], "SLEEPING FACE"],
    ["\u{1F61F}", [:worried], "WORRIED FACE"],
    ["\u{1F626}", [:frowning], "FROWNING FACE WITH OPEN MOUTH"],
    ["\u{1F627}", [:anguished], "ANGUISHED FACE"],
    ["\u{1F62E}", [:open_mouth], "FACE WITH OPEN MOUTH"],
    ["\u{1F62C}", [:grimacing], "GRIMACING FACE"],
    ["\u{1F615}", [:confused], "CONFUSED FACE"],
    ["\u{1F62F}", [:hushed], "HUSHED FACE"],
    ["\u{1F611}", [:expressionless], "EXPRESSIONLESS FACE"],
    ["\u{1F612}", [:unamused], "UNAMUSED FACE"],
    ["\u{1F605}", [:sweat_smile], "SMILING FACE WITH OPEN MOUTH AND COLD SWEAT"],
    ["\u{1F613}", [:sweat], "FACE WITH COLD SWEAT"],
    ["\u{1F629}", [:weary], "WEARY FACE"],
    ["\u{1F614}", [:pensive], "PENSIVE FACE"],
    ["\u{1F61E}", [:disappointed], "DISAPPOINTED FACE"],
    ["\u{1F616}", [:confounded], "CONFOUNDED FACE"],
    ["\u{1F628}", [:fearful], "FEARFUL FACE"],
    ["\u{1F630}", [:cold_sweat], "FACE WITH OPEN MOUTH AND COLD SWEAT"],
    ["\u{1F623}", [:persevere], "PERSEVERING FACE"],
    ["\u{1F622}", [:cry], "CRYING FACE"],
    ["\u{1F62D}", [:sob], "LOUDLY CRYING FACE"],
    ["\u{1F602}", [:joy], "FACE WITH TEARS OF JOY"],
    ["\u{1F632}", [:astonished], "ASTONISHED FACE"],
    ["\u{1F631}", [:scream], "FACE SCREAMING IN FEAR"],
    ["\u{1F62B}", [:tired_face]],
    ["\u{1F620}", [:angry], "ANGRY FACE"],
    ["\u{1F621}", [:rage], "POUTING FACE"],
    ["\u{1F624}", [:triumph], "FACE WITH LOOK OF TRIUMPH"],
    ["\u{1F62A}", [:sleepy], "SLEEPY FACE"],
    ["\u{1F60B}", [:yum], "FACE SAVOURING DELICIOUS FOOD"],
    ["\u{1F637}", [:mask], "FACE WITH MEDICAL MASK"],
    ["\u{1F60E}", [:sunglasses], "SMILING FACE WITH SUNGLASSES"],
    ["\u{1F635}", [:dizzy_face]],
    ["\u{1F47F}", [:imp]],
    ["\u{1F608}", [:smiling_imp], "SMILING FACE WITH HORNS"],
    ["\u{1F610}", [:neutral_face]],
    ["\u{1F636}", [:no_mouth], "FACE WITHOUT MOUTH"],
    ["\u{1F607}", [:innocent], "SMILING FACE WITH HALO"],
    ["\u{1F47D}", [:alien], "EXTRATERRESTRIAL ALIEN"],
    ["\u{1F49B}", [:yellow_heart]],
    ["\u{1F499}", [:blue_heart]],
    ["\u{1F49C}", [:purple_heart]],
    ["\u{2764}" , [:heart], "HEAVY BLACK HEART"],
    ["\u{1F49A}", [:green_heart]],
    ["\u{1F494}", [:broken_heart]],
    ["\u{1F493}", [:heartbeat], "BEATING HEART"],
    ["\u{1F497}", [:heartpulse], "GROWING HEART"],
    ["\u{1F495}", [:two_hearts]],
    ["\u{1F49E}", [:revolving_hearts]],
    ["\u{1F498}", [:cupid], "HEART WITH ARROW"],
    ["\u{1F496}", [:sparkling_heart]],
    ["\u{2728}" , [:sparkles]],
    ["\u{2B50}" , [:star], "WHITE MEDIUM STAR"],
    ["\u{1F31F}", [:star2], "GLOWING STAR"],
    ["\u{1F4AB}", [:dizzy], "DIZZY SYMBOL"],
    ["\u{1F4A5}", [:boom, :collision], "COLLISION SYMBOL"],
    ["\u{1F4A2}", [:anger], "ANGER SYMBOL"],
    ["\u{2757}" , [:exclamation], "HEAVY EXCLAMATION MARK SYMBOL"],
    ["\u{2753}" , [:question], "BLACK QUESTION MARK ORNAMENT"],
    ["\u{2755}" , [:grey_exclamation], "WHITE EXCLAMATION MARK ORNAMENT"],
    ["\u{2754}" , [:grey_question], "WHITE QUESTION MARK ORNAMENT"],
    ["\u{1F4A4}", [:zzz], "SLEEPING SYMBOL"],
    ["\u{1F4A8}", [:dash], "DASH SYMBOL"],
    ["\u{1F4A6}", [:sweat_drops], "SPLASHING SWEAT SYMBOL"],
    ["\u{1F3B6}", [:notes], "MULTIPLE MUSICAL NOTES"],
    ["\u{1F3B5}", [:musical_note]],
    ["\u{1F525}", [:fire], "FIRE"],
    ["\u{1F4A9}", [:hankey, :poop, :shit], "PILE OF POO"],
    ["\u{1F44D}", [:thumbsup, :"+1"], "THUMBS UP SIGN"],
    ["\u{1F44E}", [:thumbsdown, :"-1"], "THUMBS DOWN SIGN"],
    ["\u{1F44C}", [:ok_hand], "OK HAND SIGN"],
    ["\u{1F44A}", [:punch, :facepunch], "FISTED HAND SIGN"],
    ["\u{270A}" , [:fist], "RAISED FIST"],
    ["\u{270C}" , [:v], "VICTORY HAND"],
    ["\u{1F44B}", [:wave], "WAVING HAND SIGN"],
    ["\u{270B}" , [:hand], "RAISED HAND"],
    ["\u{1F450}", [:open_hands], "OPEN HANDS SIGN"],
    ["\u{261D}" , [:point_up], "WHITE UP POINTING INDEX"],
    ["\u{1F447}", [:point_down], "WHITE DOWN POINTING BACKHAND INDEX"],
    ["\u{1F448}", [:point_left], "WHITE LEFT POINTING BACKHAND INDEX"],
    ["\u{1F449}", [:point_right], "WHITE RIGHT POINTING BACKHAND INDEX"],
    ["\u{1F64C}", [:raised_hands], "PERSON RAISING BOTH HANDS IN CELEBRATION"],
    ["\u{1F64F}", [:pray], "PERSON WITH FOLDED HANDS"],
    ["\u{1F446}", [:point_up_2], "WHITE UP POINTING BACKHAND INDEX"],
    ["\u{1F44F}", [:clap], "CLAPPING HANDS SIGN"],
    ["\u{1F4AA}", [:muscle], "FLEXED BICEPS"],
    ["\u{1F6B6}", [:walking], "PEDESTRIAN"],
    ["\u{1F3C3}", [:runner, :running]],
    ["\u{1F46B}", [:couple], "MAN AND WOMAN HOLDING HANDS"],
    ["\u{1F46A}", [:family]],
    ["\u{1F46C}", [:two_men_holding_hands]],
    ["\u{1F46D}", [:two_women_holding_hands]],
    ["\u{1F483}", [:dancer]],
    ["\u{1F46F}", [:dancers], "WOMAN WITH BUNNY EARS"],
    ["\u{1F646}", [:ok_woman], "FACE WITH OK GESTURE"],
    ["\u{1F645}", [:no_good], "FACE WITH NO GOOD GESTURE"],
    ["\u{1F481}", [:information_desk_person]],
    ["\u{1F64B}", [:raised_hand], "HAPPY PERSON RAISING ONE HAND"],
    ["\u{1F470}", [:bride_with_veil]],
    ["\u{1F64E}", [:person_with_pouting_face]],
    ["\u{1F64D}", [:person_frowning]],
    ["\u{1F647}", [:bow], "PERSON BOWING DEEPLY"],
    ["\u{1F48F}", [:couplekiss], "KISS"],
    ["\u{1F491}", [:couple_with_heart]],
    ["\u{1F486}", [:massage], "FACE MASSAGE"],
    ["\u{1F487}", [:haircut]],
    ["\u{1F485}", [:nail_care], "NAIL POLISH"],
    ["\u{1F466}", [:boy]],
    ["\u{1F467}", [:girl]],
    ["\u{1F469}", [:woman]],
    ["\u{1F468}", [:man]],
    ["\u{1F476}", [:baby]],
    ["\u{1F475}", [:older_woman]],
    ["\u{1F474}", [:older_man]],
    ["\u{1F471}", [:person_with_blond_hair]],
    ["\u{1F472}", [:man_with_gua_pi_mao]],
    ["\u{1F473}", [:man_with_turban]],
    ["\u{1F477}", [:construction_worker]],
    ["\u{1F46E}", [:cop], "POLICE OFFICER"],
    ["\u{1F47C}", [:angel], "BABY ANGEL"],
    ["\u{1F478}", [:princess]],
    ["\u{1F63A}", [:smiley_cat], "SMILING CAT FACE WITH OPEN MOUTH"],
    ["\u{1F638}", [:smile_cat], "GRINNING CAT FACE WITH SMILING EYES"],
    ["\u{1F63B}", [:heart_eyes_cat], "SMILING CAT FACE WITH HEART-SHAPED EYES"],
    ["\u{1F63D}", [:kissing_cat], "KISSING CAT FACE WITH CLOSED EYES"],
    ["\u{1F63C}", [:smirk_cat], "CAT FACE WITH WRY SMILE"],
    ["\u{1F640}", [:scream_cat], "WEARY CAT FACE"],
    ["\u{1F63F}", [:crying_cat_face], "CRYING CAT FACE"],
    ["\u{1F639}", [:joy_cat], "CAT FACE WITH TEARS OF JOY"],
    ["\u{1F63E}", [:pouting_cat], "POUTING CAT FACE"],
    ["\u{1F479}", [:japanese_ogre]],
    ["\u{1F47A}", [:japanese_goblin]],
    ["\u{1F648}", [:see_no_evil], "SEE-NO-EVIL MONKEY"],
    ["\u{1F649}", [:hear_no_evil], "HEAR-NO-EVIL MONKEY"],
    ["\u{1F64A}", [:speak_no_evil], "SPEAK-NO-EVIL MONKEY"],
    ["\u{1F482}", [:guardsman]],
    ["\u{1F480}", [:skull]],
    ["\u{1F463}", [:feet], "FOOTPRINTS"],
    ["\u{1F444}", [:lips], "MOUTH"],
    ["\u{1F48B}", [:kiss], "KISS MARK"],
    ["\u{1F4A7}", [:droplet]],
    ["\u{1F442}", [:ear]],
    ["\u{1F440}", [:eyes]],
    ["\u{1F443}", [:nose]],
    ["\u{1F445}", [:tongue]],
    ["\u{1F48C}", [:love_letter]],
    ["\u{1F464}", [:bust_in_silhouette]],
    ["\u{1F465}", [:busts_in_silhouette]],
    ["\u{1F4AC}", [:speech_balloon]],
    ["\u{1F4AD}", [:thought_balloon]]
  ]

  def to_cheat_sheet(text)
    result = String.new(text)

    ATTRIBUTES.each do |codepoints, cheat_sheet_codes, description|
      result.gsub!(codepoints, ":#{cheat_sheet_codes.first.to_s}:")
    end

    result
  end

  def to_emoji(text)
    result = String.new(text)

    ATTRIBUTES.each do |codepoints, cheat_sheet_codes, description|
      cheat_sheet_codes.each do |cheat_sheet_code|
        result.gsub!(":#{cheat_sheet_code.to_s}:", codepoints)
      end
    end

    result
  end
end
