require "encoji/version"

module Encoji
  extend self

  ATTRIBUTES = [
    # Codepoints | Cheat sheet codes | Description

    # Nature
    ["\u{2600}", [:sunny], "BLACK SUN WITH RAYS"],
    ["\u{2614}", [:umbrella], "UMBRELLA WITH RAIN DROPS"],
    ["\u{2601}", [:cloud]],
    ["\u{2744}", [:snowflake]],
    ["\u{26C4}", [:snowman], "SNOWMAN WITHOUT SNOW"],
    ["\u{26A1}", [:zap], "HIGH VOLTAGE SIGN"],
    ["\u{1F300}", [:cyclone]],
    ["\u{1F301}", [:foggy]],
    ["\u{1F30A}", [:ocean], "WATER WAVE"],
    ["\u{1F431}", [:cat], "CAT FACE"],
    ["\u{1F436}", [:dog], "DOG FACE"],
    ["\u{1F42D}", [:mouse], "MOUSE FACE"],
    ["\u{1F439}", [:hamster], "HAMSTER FACE"],
    ["\u{1F430}", [:rabbit], "RABBIT FACE"],
    ["\u{1F43A}", [:wolf], "WOLF FACE"],
    ["\u{1F438}", [:frog], "FROG FACE"],
    ["\u{1F42F}", [:tiger], "TIGER FACE"],
    ["\u{1F428}", [:koala]],
    ["\u{1F43B}", [:bear], "BEAR FACE"],
    ["\u{1F437}", [:pig], "PIG FACE"],
    ["\u{1F43D}", [:pig_nose]],
    ["\u{1F42E}", [:cow], "COW FACE"],
    ["\u{1F417}", [:boar]],
    ["\u{1F435}", [:monkey_face]],
    ["\u{1F412}", [:monkey]],
    ["\u{1F434}", [:horse], "HORSE FACE"],
    ["\u{1F40E}", [:racehorse], "HORSE"],
    ["\u{1F42B}", [:camel], "BACTRIAN CAMEL"],
    ["\u{1F411}", [:sheep]],
    ["\u{1F418}", [:elephant]],
    ["\u{1F43C}", [:panda_face]],
    ["\u{1F40D}", [:snake]],
    ["\u{1F426}", [:bird]],
    ["\u{1F424}", [:baby_chick]],
    ["\u{1F425}", [:hatched_chick], "FRONT-FACING BABY CHICK"],
    ["\u{1F423}", [:hatching_chick]],
    ["\u{1F414}", [:chicken]],
    ["\u{1F427}", [:penguin]],
    ["\u{1F422}", [:turtle]],
    ["\u{1F41B}", [:bug]],
    ["\u{1F41D}", [:honeybee]],
    ["\u{1F41C}", [:ant]],
    ["\u{1F41E}", [:beetle], "LADY BEETLE"],
    ["\u{1F40C}", [:snail]],
    ["\u{1F419}", [:octopus]],
    ["\u{1F420}", [:tropical_fish]],
    ["\u{1F41F}", [:fish]],
    ["\u{1F433}", [:whale], "SPOUTING WHALE"],
    ["\u{1F40B}", [:whale2], "WHALE"],
    ["\u{1F42C}", [:dolphin]],
    ["\u{1F404}", [:cow2], "COW"],
    ["\u{1F40F}", [:ram]],
    ["\u{1F400}", [:rat]],
    ["\u{1F403}", [:water_buffalo]],
    ["\u{1F405}", [:tiger2], "TIGER"],
    ["\u{1F407}", [:rabbit2], "RABBIT"],
    ["\u{1F409}", [:dragon]],
    ["\u{1F410}", [:goat]],
    ["\u{1F413}", [:rooster]],
    ["\u{1F415}", [:dog2], "DOG"],
    ["\u{1F416}", [:pig2], "PIG"],
    ["\u{1F401}", [:mouse2], "MOUSE"],
    ["\u{1F402}", [:ox]],
    ["\u{1F432}", [:dragon_face]],
    ["\u{1F421}", [:blowfish]],
    ["\u{1F40A}", [:crocodile]],
    ["\u{1F42A}", [:dromedary_camel]],
    ["\u{1F406}", [:leopard]],
    ["\u{1F408}", [:cat2], "CAT"],
    ["\u{1F429}", [:poodle]],
    ["\u{1F43E}", [:paw_prints]],
    ["\u{1F490}", [:bouquet]],
    ["\u{1F338}", [:cherry_blossom]],
    ["\u{1F337}", [:tulip]],
    ["\u{1F340}", [:four_leaf_clover]],
    ["\u{1F339}", [:rose]],
    ["\u{1F33B}", [:sunflower]],
    ["\u{1F33A}", [:hibiscus]],
    ["\u{1F341}", [:maple_leaf]],
    ["\u{1F343}", [:leaves], "LEAF FLUTTERING IN WIND"],
    ["\u{1F342}", [:fallen_leaf]],
    ["\u{1F33F}", [:herb]],
    ["\u{1F344}", [:mushroom]],
    ["\u{1F335}", [:cactus]],
    ["\u{1F334}", [:palm_tree]],
    ["\u{1F332}", [:evergreen_tree]],
    ["\u{1F333}", [:deciduous_tree]],
    ["\u{1F330}", [:chestnut]],
    ["\u{1F331}", [:seedling]],
    ["\u{1F33C}", [:blossom]],
    ["\u{1F33E}", [:ear_of_rice]],
    ["\u{1F41A}", [:shell], "SPIRAL SHELL"],
    ["\u{1F310}", [:globe_with_meridians]],
    ["\u{1F31E}", [:sun_with_face]],
    ["\u{1F31D}", [:full_moon_with_face]],
    ["\u{1F31A}", [:new_moon_with_face]],
    ["\u{1F311}", [:new_moon], "NEW MOON SYMBOL"],
    ["\u{1F312}", [:waxing_crescent_moon], "WAXING CRESCENT MOON SYMBOL"],
    ["\u{1F313}", [:first_quarter_moon], "FIRST QUARTER MOON SYMBOL"],
    ["\u{1F314}", [:waxing_gibbous_moon], "WAXING GIBBOUS MOON SYMBOL"],
    ["\u{1F315}", [:full_moon], "FULL MOON SYMBOL"],
    ["\u{1F316}", [:waning_gibbous_moon], "WAINING GIBBOUS MOON SYMBOL"],
    ["\u{1F317}", [:last_quarter_moon], "LAST QUARTER MOON SYMBOL"],
    ["\u{1F318}", [:waning_crescent_moon], "WANING CRESCENT MOON SYMBOL"],
    ["\u{1F31C}", [:last_quarter_moon_with_face]],
    ["\u{1F31B}", [:first_quarter_moon_with_face]],
    ["\u{1F319}", [:moon], "CRESCENT MOON"],
    ["\u{1F30D}", [:earth_africa], "EARTH GLOBE EUROPE-AFRICA"],
    ["\u{1F30E}", [:earth_americas], "EARTH GLOBE AMERICAS"],
    ["\u{1F30F}", [:earth_asia], "EARTH GLOBE ASIA-AUSTRALIA"],
    ["\u{1F30B}", [:volcano]],
    ["\u{1F30C}", [:milky_way]],
    ["\u{26C5}", [:partly_sunny], "SUN BEHIND CLOUD"],

    # Objects
    ["\u{1F38D}", [:bamboo], "PINE DECORATION"],
    ["\u{1F49D}", [:gift_heart], "HEART WITH RIBBON"],
    ["\u{1F38E}", [:dolls], "JAPANESE DOLLS"],
    ["\u{1F49D}", [:gift_heart], "HEART WITH RIBBON"],
    ["\u{1F392}", [:school_satchel]],
    ["\u{1F393}", [:mortar_board], "GRADUATION CAP"],
    ["\u{1F38F}", [:flags], "CARP STREAMER"],
    ["\u{1F386}", [:fireworks]],
    ["\u{1F387}", [:sparkler], "FIREWORK SPARKLER"],
    ["\u{1F390}", [:wind_chime]],
    ["\u{1F391}", [:rice_scene], "MOON VIEWING CEREMONY"],
    ["\u{1F383}", [:jack_o_lantern], "JACK-O-LANTERN"],
    ["\u{1F47B}", [:ghost]],
    ["\u{1F385}", [:santa], "FATHER CHRISTMAS"],
    ["\u{1f3b1}", [:"8ball"]],
    ["\u{23f0}", [:alarm_clock]],
    ["\u{1f34e}", [:apple]],
    ["\u{1f3a8}", [:art]],
    ["\u{1f37c}", [:baby_bottle]],
    ["\u{1f388}", [:balloon]],
    ["\u{1f34c}", [:banana]],
    ["\u{1f4ca}", [:bar_chart]],
    ["\u{26be}", [:baseball]],
    ["\u{1f3c0}", [:basketball]],
    ["\u{1f6c0}", [:bath]],
    ["\u{1f6c1}", [:bathtub]],
    ["\u{1f50b}", [:battery]],
    ["\u{1f37a}", [:beer]],
    ["\u{1f37b}", [:beers]],
    ["\u{1f514}", [:bell]],
    ["\u{1f371}", [:bento]],
    ["\u{1f6b4}", [:bicyclist]],
    ["\u{1f459}", [:bikini]],
    ["\u{1f382}", [:birthday]],
    ["\u{1f0cf}", [:black_joker]],
    ["\u{2712}", [:black_nib]],
    ["\u{1f4d8}", [:blue_book]],
    ["\u{1f4a3}", [:bomb]],
    ["\u{1f516}", [:bookmark]],
    ["\u{1f4d1}", [:bookmark_tabs]],
    ["\u{1f4da}", [:books]],
    ["\u{1f462}", [:boot]],
    ["\u{1f3b3}", [:bowling]],
    ["\u{1f35e}", [:bread]],
    ["\u{1f4bc}", [:briefcase]],
    ["\u{1f4a1}", [:bulb]],
    ["\u{1f370}", [:cake]],
    ["\u{1f4c6}", [:calendar]],
    ["\u{1f4f2}", [:calling]],
    ["\u{1f4f7}", [:camera]],
    ["\u{1f36c}", [:candy]],
    ["\u{1f4c7}", [:card_index]],
    ["\u{1f4bf}", [:cd]],
    ["\u{1f4c9}", [:chart_with_downwards_trend]],
    ["\u{1f4c8}", [:chart_with_upwards_trend]],
    ["\u{1f352}", [:cherries]],
    ["\u{1f36b}", [:chocolate_bar]],
    ["\u{1f384}", [:christmas_tree]],
    ["\u{1f3ac}", [:clapper]],
    ["\u{1f4cb}", [:clipboard]],
    ["\u{1f4d5}", [:closed_book]],
    ["\u{1f510}", [:closed_lock_with_key]],
    ["\u{1f302}", [:closed_umbrella]],
    ["\u{2663}", [:clubs]],
    ["\u{1f378}", [:cocktail]],
    ["\u{2615}", [:coffee]],
    ["\u{1f4bb}", [:computer]],
    ["\u{1f38a}", [:confetti_ball]],
    ["\u{1f36a}", [:cookie]],
    ["\u{1f33d}", [:corn]],
    ["\u{1f4b3}", [:credit_card]],
    ["\u{1f451}", [:crown]],
    ["\u{1f52e}", [:crystal_ball]],
    ["\u{1f35b}", [:curry]],
    ["\u{1f36e}", [:custard]],
    ["\u{1f361}", [:dango]],
    ["\u{1f3af}", [:dart]],
    ["\u{1f4c5}", [:date]],
    ["\u{2666}", [:diamonds]],
    ["\u{1f4b5}", [:dollar]],
    ["\u{1f6aa}", [:door]],
    ["\u{1f369}", [:doughnut]],
    ["\u{1f457}", [:dress]],
    ["\u{1f4c0}", [:dvd]],
    ["\u{1f4e7}", [:"e-mail"]],
    ["\u{1f373}", [:egg]],
    ["\u{1f346}", [:eggplant]],
    ["\u{1f50c}", [:electric_plug]],
    ["\u{2709}", [:email, :envelope]],
    ["\u{1f4b6}", [:euro]],
    ["\u{1f453}", [:eyeglasses]],
    ["\u{1f4e0}", [:fax]],
    ["\u{1f4c1}", [:file_folder]],
    ["\u{1f365}", [:fish_cake]],
    ["\u{1f3a3}", [:fishing_pole_and_fish]],
    ["\u{1f526}", [:flashlight]],
    ["\u{1f4be}", [:floppy_disk]],
    ["\u{1f3b4}", [:flower_playing_cards]],
    ["\u{1f3c8}", [:football]],
    ["\u{1f374}", [:fork_and_knife]],
    ["\u{1f364}", [:fried_shrimp]],
    ["\u{1f35f}", [:fries]],
    ["\u{1f3b2}", [:game_die]],
    ["\u{1f48e}", [:gem]],
    ["\u{1f381}", [:gift]],
    ["\u{26f3}", [:golf]],
    ["\u{1f347}", [:grapes]],
    ["\u{1f34f}", [:green_apple]],
    ["\u{1f4d7}", [:green_book]],
    ["\u{1f3b8}", [:guitar]],
    ["\u{1f52b}", [:gun]],
    ["\u{1f354}", [:hamburger]],
    ["\u{1f528}", [:hammer]],
    ["\u{1f45c}", [:handbag]],
    ["\u{1f3a7}", [:headphones]],
    ["\u{2665}", [:hearts]],
    ["\u{1f506}", [:high_brightness]],
    ["\u{1f460}", [:high_heel]],
    ["\u{1f52a}", [:hocho]],
    ["\u{1f36f}", [:honey_pot]],
    ["\u{1f3c7}", [:horse_racing]],
    ["\u{231b}", [:hourglass]],
    ["\u{23f3}", [:hourglass_flowing_sand]],
    ["\u{1f368}", [:ice_cream]],
    ["\u{1f366}", [:icecream]],
    ["\u{1f4e5}", [:inbox_tray]],
    ["\u{1f4e8}", [:incoming_envelope]],
    ["\u{1f4f1}", [:iphone]],
    ["\u{1f456}", [:jeans]],
    ["\u{1f511}", [:key]],
    ["\u{1f458}", [:kimono]],
    ["\u{1f4d2}", [:ledger]],
    ["\u{1f34b}", [:lemon]],
    ["\u{1f484}", [:lipstick]],
    ["\u{1f512}", [:lock]],
    ["\u{1f50f}", [:lock_with_ink_pen]],
    ["\u{1f36d}", [:lollipop]],
    ["\u{27bf}", [:loop]],
    ["\u{1f4e2}", [:loudspeaker]],
    ["\u{1f505}", [:low_brightness]],
    ["\u{1f50d}", [:mag]],
    ["\u{1f50e}", [:mag_right]],
    ["\u{1f004}", [:mahjong]],
    ["\u{1f4eb}", [:mailbox]],
    ["\u{1f4ea}", [:mailbox_closed]],
    ["\u{1f4ec}", [:mailbox_with_mail]],
    ["\u{1f4ed}", [:mailbox_with_no_mail]],
    ["\u{1f45e}", [:mans_shoe, :shoe]],
    ["\u{1f356}", [:meat_on_bone]],
    ["\u{1f4e3}", [:mega]],
    ["\u{1f348}", [:melon]],
    ["\u{1f4dd}", [:memo, :pencil]],
    ["\u{1f3a4}", [:microphone]],
    ["\u{1f52c}", [:microscope]],
    ["\u{1f4bd}", [:minidisc]],
    ["\u{1f4b8}", [:money_with_wings]],
    ["\u{1f4b0}", [:moneybag]],
    ["\u{1f6b5}", [:mountain_bicyclist]],
    ["\u{1f3a5}", [:movie_camera]],
    ["\u{1f3b9}", [:musical_keyboard]],
    ["\u{1f3bc}", [:musical_score]],
    ["\u{1f507}", [:mute]],
    ["\u{1f4db}", [:name_badge]],
    ["\u{1f454}", [:necktie]],
    ["\u{1f4f0}", [:newspaper]],
    ["\u{1f515}", [:no_bell]],
    ["\u{1f4d3}", [:notebook]],
    ["\u{1f4d4}", [:notebook_with_decorative_cover]],
    ["\u{1f529}", [:nut_and_bolt]],
    ["\u{1f362}", [:oden]],
    ["\u{1f4c2}", [:open_file_folder]],
    ["\u{1f4d9}", [:orange_book]],
    ["\u{1f4e4}", [:outbox_tray]],
    ["\u{1f4c4}", [:page_facing_up]],
    ["\u{1f4c3}", [:page_with_curl]],
    ["\u{1f4df}", [:pager]],
    ["\u{1f4ce}", [:paperclip]],
    ["\u{1f351}", [:peach]],
    ["\u{1f350}", [:pear]],
    ["\u{270f}", [:pencil2]],
    ["\u{260e}", [:phone, :telephone]],
    ["\u{1f48a}", [:pill]],
    ["\u{1f34d}", [:pineapple]],
    ["\u{1f355}", [:pizza]],
    ["\u{1f4ef}", [:postal_horn]],
    ["\u{1f4ee}", [:postbox]],
    ["\u{1f45d}", [:pouch]],
    ["\u{1f357}", [:poultry_leg]],
    ["\u{1f4b7}", [:pound]],
    ["\u{1f45b}", [:purse]],
    ["\u{1f4cc}", [:pushpin]],
    ["\u{1f4fb}", [:radio]],
    ["\u{1f35c}", [:ramen]],
    ["\u{1f380}", [:ribbon]],
    ["\u{1f35a}", [:rice]],
    ["\u{1f359}", [:rice_ball]],
    ["\u{1f358}", [:rice_cracker]],
    ["\u{1f48d}", [:ring]],
    ["\u{1f3c9}", [:rugby_football]],
    ["\u{1f3bd}", [:running_shirt_with_sash]],
    ["\u{1f376}", [:sake]],
    ["\u{1f461}", [:sandal]],
    ["\u{1f4e1}", [:satellite]],
    ["\u{1f3b7}", [:saxophone]],
    ["\u{2702}", [:scissors]],
    ["\u{1f4dc}", [:scroll]],
    ["\u{1f4ba}", [:seat]],
    ["\u{1f367}", [:shaved_ice]],
    ["\u{1f455}", [:shirt, :tshirt]],
    ["\u{1f6bf}", [:shower]],
    ["\u{1f3bf}", [:ski]],
    ["\u{1f6ac}", [:smoking]],
    ["\u{1f3c2}", [:snowboarder]],
    ["\u{26bd}", [:soccer]],
    ["\u{1f509}", [:sound]],
    ["\u{1f47e}", [:space_invader]],
    ["\u{2660}", [:spades]],
    ["\u{1f35d}", [:spaghetti]],
    ["\u{1f50a}", [:speaker]],
    ["\u{1f372}", [:stew]],
    ["\u{1f4cf}", [:straight_ruler]],
    ["\u{1f353}", [:strawberry]],
    ["\u{1f3c4}", [:surfer]],
    ["\u{1f363}", [:sushi]],
    ["\u{1f360}", [:sweet_potato]],
    ["\u{1f3ca}", [:swimmer]],
    ["\u{1f489}", [:syringe]],
    ["\u{1f389}", [:tada]],
    ["\u{1f38b}", [:tanabata_tree]],
    ["\u{1f34a}", [:tangerine]],
    ["\u{1f375}", [:tea]],
    ["\u{1f4de}", [:telephone_receiver]],
    ["\u{1f52d}", [:telescope]],
    ["\u{1f3be}", [:tennis]],
    ["\u{1f6bd}", [:toilet]],
    ["\u{1f345}", [:tomato]],
    ["\u{1f3a9}", [:tophat]],
    ["\u{1f4d0}", [:triangular_ruler]],
    ["\u{1f3c6}", [:trophy]],
    ["\u{1f379}", [:tropical_drink]],
    ["\u{1f3ba}", [:trumpet]],
    ["\u{1f4fa}", [:tv]],
    ["\u{1f513}", [:unlock]],
    ["\u{1f4fc}", [:vhs]],
    ["\u{1f4f9}", [:video_camera]],
    ["\u{1f3ae}", [:video_game]],
    ["\u{1f3bb}", [:violin]],
    ["\u{231a}", [:watch]],
    ["\u{1f349}", [:watermelon]],
    ["\u{1f377}", [:wine_glass]],
    ["\u{1f45a}", [:womans_clothes]],
    ["\u{1f452}", [:womans_hat]],
    ["\u{1f527}", [:wrench]],
    ["\u{1f4b4}", [:yen]],

    # People
    ["\u{1F604}", [:smile], "SMILING FACE WITH OPEN MOUTH AND SMILING EYES"],
    ["\u{1F606}", [:laughing], "SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES"],
    ["\u{1F60A}", [:blush], "SMILING FACE WITH SMILING EYES"],
    ["\u{1F603}", [:smiley], "SMILING FACE WITH OPEN MOUTH"],
    ["\u{263A}", [:relaxed], "WHITE SMILING FACE"],
    ["\u{1F60F}", [:smirk], "SMIRKING FACE"],
    ["\u{1F60D}", [:heart_eyes], "SMILING FACE WITH HEART-SHAPED EYES"],
    ["\u{1F618}", [:kissing_heart], "FACE THROWING KISS"],
    ["\u{1F61A}", [:kissing_closed_eyes], "KISSING FACE WITH CLOSED EYES"],
    ["\u{1F633}", [:flushed], "FLUSHED FACE"],
    ["\u{1F625}", [:relieved], "DISAPPOINTED BUT RELIEVED FACE"],
    ["\u{1F60C}", [:satisfied], "RELIEVED FACE"],
    ["\u{1F601}", [:grin], "GRINNING FACE WITH SMILING EYES"],
    ["\u{1F609}", [:wink], "WINKING FACE"],
    ["\u{1F61C}", [:stuck_out_tongue_winking_eye, :wink2], "FACE WITH STUCK OUT TONGUE AND WINKING EYE"],
    ["\u{1F61D}", [:stuck_out_tongue_closed_eyes], "FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES"],
    ["\u{1F600}", [:grinning], "GRINNING FACE"],
    ["\u{1F617}", [:kissing], "KISSING FACE"],
    ["\u{1F619}", [:kissing_smiling_eyes], "KISSING FACE WITH SMILING EYES"],
    ["\u{1F61B}", [:stuck_out_tongue], "FACE WITH STUCK-OUT TONGUE"],
    ["\u{1F634}", [:sleeping], "SLEEPING FACE"],
    ["\u{1F61F}", [:worried], "WORRIED FACE"],
    ["\u{1F626}", [:frowning], "FROWNING FACE WITH OPEN MOUTH"],
    ["\u{1F627}", [:anguished], "ANGUISHED FACE"],
    ["\u{1F62E}", [:open_mouth], "FACE WITH OPEN MOUTH"],
    ["\u{1F62C}", [:grimacing], "GRIMACING FACE"],
    ["\u{1F615}", [:confused], "CONFUSED FACE"],
    ["\u{1F62F}", [:hushed], "HUSHED FACE"],
    ["\u{1F611}", [:expressionless], "EXPRESSIONLESS FACE"],
    ["\u{1F612}", [:unamused], "UNAMUSED FACE"],
    ["\u{1F605}", [:sweat_smile], "SMILING FACE WITH OPEN MOUTH AND COLD SWEAT"],
    ["\u{1F613}", [:sweat], "FACE WITH COLD SWEAT"],
    ["\u{1F629}", [:weary], "WEARY FACE"],
    ["\u{1F614}", [:pensive], "PENSIVE FACE"],
    ["\u{1F61E}", [:disappointed], "DISAPPOINTED FACE"],
    ["\u{1F616}", [:confounded], "CONFOUNDED FACE"],
    ["\u{1F628}", [:fearful], "FEARFUL FACE"],
    ["\u{1F630}", [:cold_sweat], "FACE WITH OPEN MOUTH AND COLD SWEAT"],
    ["\u{1F623}", [:persevere], "PERSEVERING FACE"],
    ["\u{1F622}", [:cry], "CRYING FACE"],
    ["\u{1F62D}", [:sob], "LOUDLY CRYING FACE"],
    ["\u{1F602}", [:joy], "FACE WITH TEARS OF JOY"],
    ["\u{1F632}", [:astonished], "ASTONISHED FACE"],
    ["\u{1F631}", [:scream], "FACE SCREAMING IN FEAR"],
    ["\u{1F62B}", [:tired_face]],
    ["\u{1F620}", [:angry], "ANGRY FACE"],
    ["\u{1F621}", [:rage], "POUTING FACE"],
    ["\u{1F624}", [:triumph], "FACE WITH LOOK OF TRIUMPH"],
    ["\u{1F62A}", [:sleepy], "SLEEPY FACE"],
    ["\u{1F60B}", [:yum], "FACE SAVOURING DELICIOUS FOOD"],
    ["\u{1F637}", [:mask], "FACE WITH MEDICAL MASK"],
    ["\u{1F60E}", [:sunglasses], "SMILING FACE WITH SUNGLASSES"],
    ["\u{1F635}", [:dizzy_face]],
    ["\u{1F47F}", [:imp]],
    ["\u{1F608}", [:smiling_imp], "SMILING FACE WITH HORNS"],
    ["\u{1F610}", [:neutral_face]],
    ["\u{1F636}", [:no_mouth], "FACE WITHOUT MOUTH"],
    ["\u{1F607}", [:innocent], "SMILING FACE WITH HALO"],
    ["\u{1F47D}", [:alien], "EXTRATERRESTRIAL ALIEN"],
    ["\u{1F49B}", [:yellow_heart]],
    ["\u{1F499}", [:blue_heart]],
    ["\u{1F49C}", [:purple_heart]],
    ["\u{2764}", [:heart], "HEAVY BLACK HEART"],
    ["\u{1F49A}", [:green_heart]],
    ["\u{1F494}", [:broken_heart]],
    ["\u{1F493}", [:heartbeat], "BEATING HEART"],
    ["\u{1F497}", [:heartpulse], "GROWING HEART"],
    ["\u{1F495}", [:two_hearts]],
    ["\u{1F49E}", [:revolving_hearts]],
    ["\u{1F498}", [:cupid], "HEART WITH ARROW"],
    ["\u{1F496}", [:sparkling_heart]],
    ["\u{2728}", [:sparkles]],
    ["\u{2B50}", [:star], "WHITE MEDIUM STAR"],
    ["\u{1F31F}", [:star2], "GLOWING STAR"],
    ["\u{1F4AB}", [:dizzy], "DIZZY SYMBOL"],
    ["\u{1F4A5}", [:boom, :collision], "COLLISION SYMBOL"],
    ["\u{1F4A2}", [:anger], "ANGER SYMBOL"],
    ["\u{2757}", [:exclamation], "HEAVY EXCLAMATION MARK SYMBOL"],
    ["\u{2753}", [:question], "BLACK QUESTION MARK ORNAMENT"],
    ["\u{2755}", [:grey_exclamation], "WHITE EXCLAMATION MARK ORNAMENT"],
    ["\u{2754}", [:grey_question], "WHITE QUESTION MARK ORNAMENT"],
    ["\u{1F4A4}", [:zzz], "SLEEPING SYMBOL"],
    ["\u{1F4A8}", [:dash], "DASH SYMBOL"],
    ["\u{1F4A6}", [:sweat_drops], "SPLASHING SWEAT SYMBOL"],
    ["\u{1F3B6}", [:notes], "MULTIPLE MUSICAL NOTES"],
    ["\u{1F3B5}", [:musical_note]],
    ["\u{1F525}", [:fire], "FIRE"],
    ["\u{1F4A9}", [:hankey, :poop, :shit], "PILE OF POO"],
    ["\u{1F44D}", [:thumbsup, :"+1"], "THUMBS UP SIGN"],
    ["\u{1F44E}", [:thumbsdown, :"-1"], "THUMBS DOWN SIGN"],
    ["\u{1F44C}", [:ok_hand], "OK HAND SIGN"],
    ["\u{1F44A}", [:punch, :facepunch], "FISTED HAND SIGN"],
    ["\u{270A}", [:fist], "RAISED FIST"],
    ["\u{270C}", [:v], "VICTORY HAND"],
    ["\u{1F44B}", [:wave], "WAVING HAND SIGN"],
    ["\u{270B}", [:hand], "RAISED HAND"],
    ["\u{1F450}", [:open_hands], "OPEN HANDS SIGN"],
    ["\u{261D}", [:point_up], "WHITE UP POINTING INDEX"],
    ["\u{1F447}", [:point_down], "WHITE DOWN POINTING BACKHAND INDEX"],
    ["\u{1F448}", [:point_left], "WHITE LEFT POINTING BACKHAND INDEX"],
    ["\u{1F449}", [:point_right], "WHITE RIGHT POINTING BACKHAND INDEX"],
    ["\u{1F64C}", [:raised_hands], "PERSON RAISING BOTH HANDS IN CELEBRATION"],
    ["\u{1F64F}", [:pray], "PERSON WITH FOLDED HANDS"],
    ["\u{1F446}", [:point_up_2], "WHITE UP POINTING BACKHAND INDEX"],
    ["\u{1F44F}", [:clap], "CLAPPING HANDS SIGN"],
    ["\u{1F4AA}", [:muscle], "FLEXED BICEPS"],
    ["\u{1F6B6}", [:walking], "PEDESTRIAN"],
    ["\u{1F3C3}", [:runner, :running]],
    ["\u{1F46B}", [:couple], "MAN AND WOMAN HOLDING HANDS"],
    ["\u{1F46A}", [:family]],
    ["\u{1F46C}", [:two_men_holding_hands]],
    ["\u{1F46D}", [:two_women_holding_hands]],
    ["\u{1F483}", [:dancer]],
    ["\u{1F46F}", [:dancers], "WOMAN WITH BUNNY EARS"],
    ["\u{1F646}", [:ok_woman], "FACE WITH OK GESTURE"],
    ["\u{1F645}", [:no_good], "FACE WITH NO GOOD GESTURE"],
    ["\u{1F481}", [:information_desk_person]],
    ["\u{1F64B}", [:raised_hand], "HAPPY PERSON RAISING ONE HAND"],
    ["\u{1F470}", [:bride_with_veil]],
    ["\u{1F64E}", [:person_with_pouting_face]],
    ["\u{1F64D}", [:person_frowning]],
    ["\u{1F647}", [:bow], "PERSON BOWING DEEPLY"],
    ["\u{1F48F}", [:couplekiss], "KISS"],
    ["\u{1F491}", [:couple_with_heart]],
    ["\u{1F486}", [:massage], "FACE MASSAGE"],
    ["\u{1F487}", [:haircut]],
    ["\u{1F485}", [:nail_care], "NAIL POLISH"],
    ["\u{1F466}", [:boy]],
    ["\u{1F467}", [:girl]],
    ["\u{1F469}", [:woman]],
    ["\u{1F468}", [:man]],
    ["\u{1F476}", [:baby]],
    ["\u{1F475}", [:older_woman]],
    ["\u{1F474}", [:older_man]],
    ["\u{1F471}", [:person_with_blond_hair]],
    ["\u{1F472}", [:man_with_gua_pi_mao]],
    ["\u{1F473}", [:man_with_turban]],
    ["\u{1F477}", [:construction_worker]],
    ["\u{1F46E}", [:cop], "POLICE OFFICER"],
    ["\u{1F47C}", [:angel], "BABY ANGEL"],
    ["\u{1F478}", [:princess]],
    ["\u{1F63A}", [:smiley_cat], "SMILING CAT FACE WITH OPEN MOUTH"],
    ["\u{1F638}", [:smile_cat], "GRINNING CAT FACE WITH SMILING EYES"],
    ["\u{1F63B}", [:heart_eyes_cat], "SMILING CAT FACE WITH HEART-SHAPED EYES"],
    ["\u{1F63D}", [:kissing_cat], "KISSING CAT FACE WITH CLOSED EYES"],
    ["\u{1F63C}", [:smirk_cat], "CAT FACE WITH WRY SMILE"],
    ["\u{1F640}", [:scream_cat], "WEARY CAT FACE"],
    ["\u{1F63F}", [:crying_cat_face], "CRYING CAT FACE"],
    ["\u{1F639}", [:joy_cat], "CAT FACE WITH TEARS OF JOY"],
    ["\u{1F63E}", [:pouting_cat], "POUTING CAT FACE"],
    ["\u{1F479}", [:japanese_ogre]],
    ["\u{1F47A}", [:japanese_goblin]],
    ["\u{1F648}", [:see_no_evil], "SEE-NO-EVIL MONKEY"],
    ["\u{1F649}", [:hear_no_evil], "HEAR-NO-EVIL MONKEY"],
    ["\u{1F64A}", [:speak_no_evil], "SPEAK-NO-EVIL MONKEY"],
    ["\u{1F482}", [:guardsman]],
    ["\u{1F480}", [:skull]],
    ["\u{1F463}", [:feet], "FOOTPRINTS"],
    ["\u{1F444}", [:lips], "MOUTH"],
    ["\u{1F48B}", [:kiss], "KISS MARK"],
    ["\u{1F4A7}", [:droplet]],
    ["\u{1F442}", [:ear]],
    ["\u{1F440}", [:eyes]],
    ["\u{1F443}", [:nose]],
    ["\u{1F445}", [:tongue]],
    ["\u{1F48C}", [:love_letter]],
    ["\u{1F464}", [:bust_in_silhouette]],
    ["\u{1F465}", [:busts_in_silhouette]],
    ["\u{1F4AC}", [:speech_balloon]],
    ["\u{1F4AD}", [:thought_balloon]],

    # Places
    ["\u{1f6a1}", [:aerial_tramway]],
    ["\u{2708}", [:airplane]],
    ["\u{1f691}", [:ambulance]],
    ["\u{2693}", [:anchor]],
    ["\u{1f69b}", [:articulated_lorry]],
    ["\u{1f3e7}", [:atm]],
    ["\u{1f3e6}", [:bank]],
    ["\u{1f488}", [:barber]],
    ["\u{1f530}", [:beginner]],
    ["\u{1f6b2}", [:bike]],
    ["\u{1f699}", [:blue_car]],
    ["\u{26f5}", [:boat, :sailboat]],
    ["\u{1f309}", [:bridge_at_night]],
    ["\u{1f685}", [:bullettrain_front]],
    ["\u{1f684}", [:bullettrain_side]],
    ["\u{1f68c}", [:bus]],
    ["\u{1f68f}", [:busstop]],
    ["\u{1f697}", [:car, :red_car]],
    ["\u{1f3a0}", [:carousel_horse]],
    ["\u{1f3c1}", [:checkered_flag]],
    ["\u{26ea}", [:church]],
    ["\u{1f3aa}", [:circus_tent]],
    ["\u{1f307}", [:city_sunrise]],
    ["\u{1f306}", [:city_sunset]],
    ["\u{1f6a7}", [:construction]],
    ["\u{1f3ea}", [:convenience_store]],
    ["\u{1f38c}", [:crossed_flags]],
    ["\u{1f3ec}", [:department_store]],
    ["\u{1f3f0}", [:european_castle]],
    ["\u{1f3e4}", [:european_post_office]],
    ["\u{1f3ed}", [:factory]],
    ["\u{1f3a1}", [:ferris_wheel]],
    ["\u{1f692}", [:fire_engine]],
    ["\u{26f2}", [:fountain]],
    ["\u{26fd}", [:fuelpump]],
    ["\u{1f681}", [:helicopter]],
    ["\u{1f3e5}", [:hospital]],
    ["\u{1f3e8}", [:hotel]],
    ["\u{2668}", [:hotsprings]],
    ["\u{1f3e0}", [:house]],
    ["\u{1f3e1}", [:house_with_garden]],
    ["\u{1f5fe}", [:japan]],
    ["\u{1f3ef}", [:japanese_castle]],
    ["\u{1f688}", [:light_rail]],
    ["\u{1f3e9}", [:love_hotel]],
    ["\u{1f690}", [:minibus]],
    ["\u{1f69d}", [:monorail]],
    ["\u{1f5fb}", [:mount_fuji]],
    ["\u{1f6a0}", [:mountain_cableway]],
    ["\u{1f69e}", [:mountain_railway]],
    ["\u{1f5ff}", [:moyai]],
    ["\u{1f3e2}", [:office]],
    ["\u{1f698}", [:oncoming_automobile]],
    ["\u{1f68d}", [:oncoming_bus]],
    ["\u{1f694}", [:oncoming_police_car]],
    ["\u{1f696}", [:oncoming_taxi]],
    ["\u{1f3ad}", [:performing_arts]],
    ["\u{1f693}", [:police_car]],
    ["\u{1f3e3}", [:post_office]],
    ["\u{1f683}", [:railway_car, :train]],
    ["\u{1f308}", [:rainbow]],
    ["\u{1f680}", [:rocket]],
    ["\u{1f3a2}", [:roller_coaster]],
    ["\u{1f6a8}", [:rotating_light]],
    ["\u{1f4cd}", [:round_pushpin]],
    ["\u{1f6a3}", [:rowboat]],
    ["\u{1f3eb}", [:school]],
    ["\u{1f6a2}", [:ship]],
    ["\u{1f3b0}", [:slot_machine]],
    ["\u{1f6a4}", [:speedboat]],
    ["\u{1f303}", [:stars]],
    ["\u{1f689}", [:station]],
    ["\u{1f5fd}", [:statue_of_liberty]],
    ["\u{1f682}", [:steam_locomotive]],
    ["\u{1f305}", [:sunrise]],
    ["\u{1f304}", [:sunrise_over_mountains]],
    ["\u{1f69f}", [:suspension_railway]],
    ["\u{1f695}", [:taxi]],
    ["\u{26fa}", [:tent]],
    ["\u{1f3ab}", [:ticket]],
    ["\u{1f5fc}", [:tokyo_tower]],
    ["\u{1f69c}", [:tractor]],
    ["\u{1f6a5}", [:traffic_light]],
    ["\u{1f686}", [:train2]],
    ["\u{1f68a}", [:tram]],
    ["\u{1f6a9}", [:triangular_flag_on_post]],
    ["\u{1f68e}", [:trolleybus]],
    ["\u{1f69a}", [:truck]],
    ["\u{1f6a6}", [:vertical_traffic_light]],
    ["\u{26a0}", [:warning]],
    ["\u{1f492}", [:wedding]],
    ["\u{1f1ef 1f1f5}", [:jp], "REGIONAL INDICATOR SYMBOL LETTERS JP"],
    ["\u{1f1f0 1f1f7}", [:kr], "REGIONAL INDICATOR SYMBOL LETTERS KR"],
    ["\u{1f1e8 1f1f3}", [:cn], "REGIONAL INDICATOR SYMBOL LETTERS CN"],
    ["\u{1f1fa 1f1f8}", [:us], "REGIONAL INDICATOR SYMBOL LETTERS US"],
    ["\u{1f1eb 1f1f7}", [:fr], "REGIONAL INDICATOR SYMBOL LETTERS FR"],
    ["\u{1f1ea 1f1f8}", [:es], "REGIONAL INDICATOR SYMBOL LETTERS ES"],
    ["\u{1f1ee 1f1f9}", [:it], "REGIONAL INDICATOR SYMBOL LETTERS IT"],
    ["\u{1f1f7 1f1fa}", [:ru], "REGIONAL INDICATOR SYMBOL LETTERS RU"],
    ["\u{1f1ec 1f1e7}", [:gb, :uk], "REGIONAL INDICATOR SYMBOL LETTERS GB"],
    ["\u{1f1e9 1f1ea}", [:de], "REGIONAL INDICATOR SYMBOL LETTERS DE"],

    # Symbols
    ["\u{1f4af}", [:"100"]],
    ["\u{1f522}", [:"1234"]],
    ["\u{1f170}", [:a]],
    ["\u{1f18e}", [:ab]],
    ["\u{1f524}", [:abc]],
    ["\u{1f521}", [:abcd]],
    ["\u{1f251}", [:accept]],
    ["\u{2652}", [:aquarius]],
    ["\u{2648}", [:aries]],
    ["\u{25c0}", [:arrow_backward]],
    ["\u{23ec}", [:arrow_double_down]],
    ["\u{23eb}", [:arrow_double_up]],
    ["\u{2b07}", [:arrow_down]],
    ["\u{1f53d}", [:arrow_down_small]],
    ["\u{25b6}", [:arrow_forward]],
    ["\u{2935}", [:arrow_heading_down]],
    ["\u{2934}", [:arrow_heading_up]],
    ["\u{2b05}", [:arrow_left]],
    ["\u{2199}", [:arrow_lower_left]],
    ["\u{2198}", [:arrow_lower_right]],
    ["\u{27a1}", [:arrow_right]],
    ["\u{21aa}", [:arrow_right_hook]],
    ["\u{2b06}", [:arrow_up]],
    ["\u{2195}", [:arrow_up_down]],
    ["\u{1f53c}", [:arrow_up_small]],
    ["\u{2196}", [:arrow_upper_left]],
    ["\u{2197}", [:arrow_upper_right]],
    ["\u{1f503}", [:arrows_clockwise]],
    ["\u{1f504}", [:arrows_counterclockwise]],
    ["\u{1f171}", [:b]],
    ["\u{1f6bc}", [:baby_symbol]],
    ["\u{1f6c4}", [:baggage_claim]],
    ["\u{2611}", [:ballot_box_with_check]],
    ["\u{203c}", [:bangbang]],
    ["\u{26ab}", [:black_circle]],
    ["\u{1f532}", [:black_square_button]],
    ["\u{264b}", [:cancer]],
    ["\u{1f520}", [:capital_abcd]],
    ["\u{2651}", [:capricorn]],
    ["\u{1f4b9}", [:chart]],
    ["\u{1f6b8}", [:children_crossing]],
    ["\u{1f3a6}", [:cinema]],
    ["\u{1f191}", [:cl]],
    ["\u{1f550}", [:clock1]],
    ["\u{1f559}", [:clock10]],
    ["\u{1f565}", [:clock1030]],
    ["\u{1f55a}", [:clock11]],
    ["\u{1f566}", [:clock1130]],
    ["\u{1f55b}", [:clock12]],
    ["\u{1f567}", [:clock1230]],
    ["\u{1f55c}", [:clock130]],
    ["\u{1f551}", [:clock2]],
    ["\u{1f55d}", [:clock230]],
    ["\u{1f552}", [:clock3]],
    ["\u{1f55e}", [:clock330]],
    ["\u{1f553}", [:clock4]],
    ["\u{1f55f}", [:clock430]],
    ["\u{1f554}", [:clock5]],
    ["\u{1f560}", [:clock530]],
    ["\u{1f555}", [:clock6]],
    ["\u{1f561}", [:clock630]],
    ["\u{1f556}", [:clock7]],
    ["\u{1f562}", [:clock730]],
    ["\u{1f557}", [:clock8]],
    ["\u{1f563}", [:clock830]],
    ["\u{1f558}", [:clock9]],
    ["\u{1f564}", [:clock930]],
    ["\u{3297}", [:congratulations]],
    ["\u{1f192}", [:cool]],
    ["\u{00a9}", [:copyright]],
    ["\u{27b0}", [:curly_loop]],
    ["\u{1f4b1}", [:currency_exchange]],
    ["\u{1f6c3}", [:customs]],
    ["\u{1f4a0}", [:diamond_shape_with_a_dot_inside]],
    ["\u{1f6af}", [:do_not_litter]],
    ["\u{0038 20e3}", [:eight]],
    ["\u{2734}", [:eight_pointed_black_star]],
    ["\u{2733}", [:eight_spoked_asterisk]],
    ["\u{1f51a}", [:end]],
    ["\u{23e9}", [:fast_forward]],
    ["\u{0035 20e3}", [:five]],
    ["\u{0034 20e3}", [:four]],
    ["\u{1f193}", [:free]],
    ["\u{264a}", [:gemini]],
    ["\u{0023 20e3}", [:hash]],
    ["\u{1f49f}", [:heart_decoration]],
    ["\u{2714}", [:heavy_check_mark]],
    ["\u{2797}", [:heavy_division_sign]],
    ["\u{1f4b2}", [:heavy_dollar_sign]],
    ["\u{2796}", [:heavy_minus_sign]],
    ["\u{2716}", [:heavy_multiplication_x]],
    ["\u{2795}", [:heavy_plus_sign]],
    ["\u{1f194}", [:id]],
    ["\u{1f250}", [:ideograph_advantage]],
    ["\u{2139}", [:information_source]],
    ["\u{2049}", [:interrobang]],
    ["\u{1f51f}", [:keycap_ten]],
    ["\u{1f201}", [:koko]],
    ["\u{1f535}", [:large_blue_circle]],
    ["\u{1f537}", [:large_blue_diamond]],
    ["\u{1f536}", [:large_orange_diamond]],
    ["\u{1f6c5}", [:left_luggage]],
    ["\u{2194}", [:left_right_arrow]],
    ["\u{21a9}", [:leftwards_arrow_with_hook]],
    ["\u{264c}", [:leo]],
    ["\u{264e}", [:libra]],
    ["\u{1f517}", [:link]],
    ["\u{24c2}", [:m]],
    ["\u{1f6b9}", [:mens]],
    ["\u{1f687}", [:metro]],
    ["\u{1f4f4}", [:mobile_phone_off]],
    ["\u{274e}", [:negative_squared_cross_mark]],
    ["\u{1f195}", [:new]],
    ["\u{1f196}", [:ng]],
    ["\u{0039 20e3}", [:nine]],
    ["\u{1f6b3}", [:no_bicycles]],
    ["\u{26d4}", [:no_entry]],
    ["\u{1f6ab}", [:no_entry_sign]],
    ["\u{1f4f5}", [:no_mobile_phones]],
    ["\u{1f6b7}", [:no_pedestrians]],
    ["\u{1f6ad}", [:no_smoking]],
    ["\u{1f6b1}", [:"non-potable_water"]],
    ["\u{2b55}", [:o]],
    ["\u{1f17e}", [:o2]],
    ["\u{1f197}", [:ok]],
    ["\u{1f51b}", [:on]],
    ["\u{0031 20e3}", [:one]],
    ["\u{26ce}", [:ophiuchus]],
    ["\u{1f17f}", [:parking]],
    ["\u{303d}", [:part_alternation_mark]],
    ["\u{1f6c2}", [:passport_control]],
    ["\u{2653}", [:pisces]],
    ["\u{1f6b0}", [:potable_water]],
    ["\u{1f6ae}", [:put_litter_in_its_place]],
    ["\u{1f518}", [:radio_button]],
    ["\u{267b}", [:recycle]],
    ["\u{1f534}", [:red_circle]],
    ["\u{00ae}", [:registered]],
    ["\u{1f501}", [:repeat]],
    ["\u{1f502}", [:repeat_one]],
    ["\u{1f6bb}", [:restroom]],
    ["\u{23ea}", [:rewind]],
    ["\u{1f202}", [:sa]],
    ["\u{2650}", [:sagittarius]],
    ["\u{264f}", [:scorpius]],
    ["\u{3299}", [:secret]],
    ["\u{0037 20e3}", [:seven]],
    ["\u{1f4f6}", [:signal_strength]],
    ["\u{0036 20e3}", [:six]],
    ["\u{1f52f}", [:six_pointed_star]],
    ["\u{1f539}", [:small_blue_diamond]],
    ["\u{1f538}", [:small_orange_diamond]],
    ["\u{1f53a}", [:small_red_triangle]],
    ["\u{1f53b}", [:small_red_triangle_down]],
    ["\u{1f51c}", [:soon]],
    ["\u{1f198}", [:sos]],
    ["\u{1f523}", [:symbols]],
    ["\u{2649}", [:taurus]],
    ["\u{0033 20e3}", [:three]],
    ["\u{2122}", [:tm]],
    ["\u{1f51d}", [:top]],
    ["\u{1f531}", [:trident]],
    ["\u{1f500}", [:twisted_rightwards_arrows]],
    ["\u{0032 20e3}", [:two]],
    ["\u{1f239}", [:u5272]],
    ["\u{1f234}", [:u5408]],
    ["\u{1f23a}", [:u55b6]],
    ["\u{1f22f}", [:u6307]],
    ["\u{1f237}", [:u6708]],
    ["\u{1f236}", [:u6709]],
    ["\u{1f235}", [:u6e80]],
    ["\u{1f21a}", [:u7121]],
    ["\u{1f238}", [:u7533]],
    ["\u{1f232}", [:u7981]],
    ["\u{1f233}", [:u7a7a]],
    ["\u{1f51e}", [:underage]],
    ["\u{1f199}", [:up]],
    ["\u{1f4f3}", [:vibration_mode]],
    ["\u{264d}", [:virgo]],
    ["\u{1f19a}", [:vs]],
    ["\u{3030}", [:wavy_dash]],
    ["\u{1f6be}", [:wc]],
    ["\u{267f}", [:wheelchair]],
    ["\u{2705}", [:white_check_mark]],
    ["\u{26aa}", [:white_circle]],
    ["\u{1f4ae}", [:white_flower]],
    ["\u{1f533}", [:white_square_button]],
    ["\u{1f6ba}", [:womens]],
    ["\u{274c}", [:x]],
    ["\u{0030 20e3}", [:zero]]
  ]

  def to_cheat_sheet(text)
    result = String.new(text)

    ATTRIBUTES.each do |codepoints, cheat_sheet_codes, description|
      result.gsub!(codepoints, ":#{cheat_sheet_codes.first.to_s}:")
    end

    result
  end

  def to_emoji(text)
    result = String.new(text)

    ATTRIBUTES.each do |codepoints, cheat_sheet_codes, description|
      cheat_sheet_codes.each do |cheat_sheet_code|
        result.gsub!(":#{cheat_sheet_code.to_s}:", codepoints)
      end
    end

    result
  end
end
